# Generated by Django 3.2.3 on 2021-09-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmart_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmart_app.seller'),
        ),
    ]
