# Generated by Django 3.2.3 on 2021-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmart_app', '0003_rename_product_added_by_product_product_added_by_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_product_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
