# Generated by Django 3.2.3 on 2021-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmart_app', '0004_product_total_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_images',
            field=models.ImageField(default='', upload_to='seller_images'),
        ),
    ]
