# Generated by Django 3.2.3 on 2021-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmart_app', '0005_alter_seller_seller_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
